/**
 * Data Pools for 500 Test User Generation
 *
 * - Census-based names (~2004 birth year for 20-year-olds)
 * - Attribute mixers for diverse AI image prompts
 */

// =============================================================================
// MALE NAMES (Top 250 from ~2004 Social Security data)
// =============================================================================
export const MALE_NAMES = [
	// Top 50
	"Liam",
	"Noah",
	"Ethan",
	"Aiden",
	"Jacob",
	"Lucas",
	"Mason",
	"Logan",
	"James",
	"Benjamin",
	"Elijah",
	"Oliver",
	"Michael",
	"Daniel",
	"Matthew",
	"Alexander",
	"William",
	"Henry",
	"Sebastian",
	"Jack",
	"Owen",
	"Samuel",
	"Ryan",
	"Nathan",
	"Joseph",
	"David",
	"Dylan",
	"Andrew",
	"Luke",
	"Isaac",
	"Gabriel",
	"Anthony",
	"Joshua",
	"Christopher",
	"Caleb",
	"Tyler",
	"Jayden",
	"Christian",
	"Jonathan",
	"Landon",
	"Cameron",
	"Brandon",
	"Angel",
	"Austin",
	"Connor",
	"Adrian",
	"Evan",
	"Jordan",
	"Nicholas",
	"Jeremiah",
	// 51-100
	"Hunter",
	"Robert",
	"Aaron",
	"Thomas",
	"Eli",
	"Charles",
	"Gavin",
	"Jaxon",
	"Isaiah",
	"Jason",
	"Lincoln",
	"Julian",
	"Adam",
	"Kevin",
	"Zachary",
	"Jose",
	"Nolan",
	"Cooper",
	"Parker",
	"Xavier",
	"Carson",
	"Dominic",
	"Miles",
	"Ian",
	"Easton",
	"Leo",
	"Brayden",
	"Tristan",
	"Damian",
	"Brody",
	"Jaden",
	"Mateo",
	"Colton",
	"Vincent",
	"Blake",
	"Cole",
	"Asher",
	"Grayson",
	"Hayden",
	"Diego",
	"Maxwell",
	"Adam",
	"Eric",
	"Nathaniel",
	"Justin",
	"Axel",
	"Roman",
	"Steven",
	"Patrick",
	"Kenneth",
	// 101-150
	"Marcus",
	"Declan",
	"Jace",
	"Harrison",
	"Jesse",
	"Victor",
	"Preston",
	"Oscar",
	"Sean",
	"Derek",
	"Wesley",
	"Cayden",
	"George",
	"Max",
	"Emmett",
	"Bryan",
	"Timothy",
	"Travis",
	"Peter",
	"Fernando",
	"Joel",
	"Richard",
	"Edward",
	"Brian",
	"Trevor",
	"Ricardo",
	"Brady",
	"Kaden",
	"Grant",
	"Erik",
	"Miguel",
	"Alan",
	"Bradley",
	"Shane",
	"Simon",
	"Martin",
	"Edgar",
	"Paul",
	"Giovanni",
	"Jorge",
	"Jonah",
	"Alejandro",
	"Kyle",
	"Marcos",
	"Tucker",
	"Abraham",
	"Andres",
	"Frank",
	"Jaime",
	"Raymond",
	// 151-200
	"Sergio",
	"Dustin",
	"Tanner",
	"Cesar",
	"Marco",
	"Colin",
	"Cody",
	"Omar",
	"Roberto",
	"Rafael",
	"Spencer",
	"Corey",
	"Lane",
	"Griffin",
	"Drew",
	"Ruben",
	"Carlos",
	"Ivan",
	"Phillip",
	"Alberto",
	"Francisco",
	"Andy",
	"Danny",
	"Dalton",
	"Gregory",
	"Mitchell",
	"Brett",
	"Ronald",
	"Manuel",
	"Armando",
	"Scott",
	"Gerardo",
	"Hector",
	"Luis",
	"Jaylen",
	"Johnathan",
	"Malik",
	"Maurice",
	"Trent",
	"Jared",
	"Keith",
	"Larry",
	"Kristopher",
	"Derrick",
	"Devin",
	"Dillon",
	"Erik",
	"Raymond",
	"Gerald",
	"Louis",
	// 201-250
	"Trenton",
	"Curtis",
	"Rodney",
	"Jaiden",
	"Lance",
	"Brennan",
	"Skyler",
	"Ross",
	"Darius",
	"Ricky",
	"Clayton",
	"Dennis",
	"Francis",
	"Riley",
	"Pedro",
	"Alec",
	"Braden",
	"Russell",
	"Terrance",
	"Colby",
	"Jeffery",
	"Reginald",
	"Enrique",
	"Donovan",
	"Nickolas",
	"Braxton",
	"Chad",
	"Troy",
	"Caden",
	"Randy",
	"Dean",
	"Nicolas",
	"Fabian",
	"Tyrone",
	"Brendon",
	"Deandre",
	"Jarrett",
	"Quinton",
	"Marquis",
	"Malcolm",
	"Micah",
	"Zackary",
	"Chance",
	"Blaine",
	"Quincy",
	"Kendall",
	"Saul",
	"Tyson",
	"Ashton",
	"Brock",
];

// =============================================================================
// FEMALE NAMES (Top 250 from ~2004 Social Security data)
// =============================================================================
export const FEMALE_NAMES = [
	// Top 50
	"Emma",
	"Olivia",
	"Ava",
	"Isabella",
	"Sophia",
	"Mia",
	"Charlotte",
	"Amelia",
	"Harper",
	"Evelyn",
	"Abigail",
	"Emily",
	"Ella",
	"Elizabeth",
	"Sofia",
	"Avery",
	"Camila",
	"Scarlett",
	"Victoria",
	"Madison",
	"Luna",
	"Grace",
	"Chloe",
	"Penelope",
	"Riley",
	"Zoey",
	"Nora",
	"Lily",
	"Eleanor",
	"Hannah",
	"Lillian",
	"Addison",
	"Aubrey",
	"Ellie",
	"Stella",
	"Natalie",
	"Zoe",
	"Leah",
	"Hazel",
	"Violet",
	"Aurora",
	"Savannah",
	"Audrey",
	"Brooklyn",
	"Bella",
	"Claire",
	"Skylar",
	"Lucy",
	"Paisley",
	"Anna",
	// 51-100
	"Caroline",
	"Genesis",
	"Aaliyah",
	"Kennedy",
	"Kinsley",
	"Allison",
	"Maya",
	"Sarah",
	"Madelyn",
	"Adeline",
	"Alexa",
	"Ariana",
	"Elena",
	"Gabriella",
	"Naomi",
	"Alice",
	"Sadie",
	"Hailey",
	"Eva",
	"Emilia",
	"Autumn",
	"Quinn",
	"Nevaeh",
	"Piper",
	"Ruby",
	"Serenity",
	"Willow",
	"Everly",
	"Cora",
	"Kaylee",
	"Lydia",
	"Aubree",
	"Arianna",
	"Eliana",
	"Peyton",
	"Melanie",
	"Gianna",
	"Isabelle",
	"Julia",
	"Valentina",
	"Nova",
	"Clara",
	"Vivian",
	"Reagan",
	"Mackenzie",
	"Madeline",
	"Brielle",
	"Delilah",
	"Isla",
	"Rylee",
	// 101-150
	"Katherine",
	"Sophie",
	"Josephine",
	"Ivy",
	"Liliana",
	"Jade",
	"Maria",
	"Taylor",
	"Hadley",
	"Kylie",
	"Emery",
	"Adalynn",
	"Natalia",
	"Annabelle",
	"Faith",
	"Alexandra",
	"Ximena",
	"Ashley",
	"Brianna",
	"Raelynn",
	"Bailey",
	"Mary",
	"Athena",
	"Andrea",
	"Leilani",
	"Jasmine",
	"Lyla",
	"Margaret",
	"Alyssa",
	"Adalyn",
	"Arya",
	"Norah",
	"Khloe",
	"Kayla",
	"Payton",
	"Jordyn",
	"Layla",
	"Eden",
	"Rose",
	"Melody",
	"Alexis",
	"Isabel",
	"Sydney",
	"Lauren",
	"London",
	"Morgan",
	"Lilly",
	"Charlie",
	"Aliyah",
	"Valeria",
	// 151-200
	"Arabella",
	"Sara",
	"Finley",
	"Trinity",
	"Ryleigh",
	"Jordyn",
	"Jocelyn",
	"Kimberly",
	"Esther",
	"Molly",
	"Valerie",
	"Cecilia",
	"Anastasia",
	"Daisy",
	"Reese",
	"Laila",
	"Myla",
	"Amy",
	"Teagan",
	"Amaya",
	"Elise",
	"Harmony",
	"Paige",
	"Adaline",
	"Fiona",
	"Alaina",
	"Nicole",
	"Genevieve",
	"Lucia",
	"Alina",
	"Mckenzie",
	"Callie",
	"Brooke",
	"Londyn",
	"Summer",
	"Julianna",
	"Michelle",
	"Gracie",
	"Juliette",
	"Sienna",
	"Eliza",
	"Rachel",
	"Daniela",
	"Juliana",
	"Mariah",
	"Vanessa",
	"Angela",
	"Presley",
	"Adriana",
	"Brooklynn",
	// 201-250
	"Catherine",
	"Leila",
	"Lola",
	"Angelina",
	"Hope",
	"Tessa",
	"Alayna",
	"Emersyn",
	"Maci",
	"Aspen",
	"Elsie",
	"Kate",
	"Diana",
	"Stephanie",
	"Nina",
	"Mckenna",
	"Gemma",
	"Lena",
	"Hayden",
	"Rebecca",
	"Jennifer",
	"Ana",
	"Camille",
	"Maggie",
	"Makenzie",
	"Iris",
	"Shelby",
	"Amanda",
	"Chelsea",
	"Destiny",
	"Marley",
	"Keira",
	"Jessica",
	"Vera",
	"Adrianna",
	"Kenzie",
	"Breanna",
	"Brittany",
	"Daleyza",
	"Danielle",
	"Tiffany",
	"Megan",
	"Kelsey",
	"Brynn",
	"Aleah",
	"Jayda",
	"Cassidy",
	"Janelle",
	"Selena",
	"Josie",
];

// =============================================================================
// ATTRIBUTE MIXERS (For diverse AI prompts)
// =============================================================================

/** 7 ethnicities for visual diversity */
export const ETHNICITIES = [
	"Asian",
	"Latino",
	"White",
	"Black",
	"South Asian",
	"Middle Eastern",
	"Mixed Race",
];

/** Hair styles - diverse options for both genders */
export const HAIR_STYLES = [
	// Long hair styles
	"long straight hair",
	"long wavy hair",
	"long curly hair",
	"loose waves",
	"beachy waves",
	"layered long hair",
	// Medium length
	"shoulder-length hair",
	"lob haircut",
	"medium curly hair",
	"shaggy hair",
	// Short hair
	"pixie cut",
	"bob haircut",
	"short curly hair",
	"buzz cut",
	"crew cut",
	"short fade",
	"undercut",
	"textured crop",
	// Updos & Tied
	"messy bun",
	"high ponytail",
	"low ponytail",
	"braids",
	"space buns",
	"half up half down",
	// Textured & Natural
	"afro",
	"box braids",
	"dreadlocks",
	"cornrows",
	"natural coils",
	// Bangs & Fringes
	"hair with bangs",
	"curtain bangs",
	"side swept fringe",
];

/** Clothing options - diverse styles for college students */
export const CLOTHING = [
	// Casual tops
	"University hoodie",
	"vintage band tee",
	"plain white t-shirt",
	"graphic tee",
	"crop top",
	"tank top",
	"polo shirt",
	"henley shirt",
	// Shirts & Blouses
	"flannel shirt",
	"denim shirt",
	"button-down oxford shirt",
	"oversized shirt",
	// Jackets & Outerwear
	"puffer jacket",
	"denim jacket",
	"leather jacket",
	"varsity jacket",
	"windbreaker",
	"cardigan",
	// Sporty
	"soccer jersey",
	"basketball jersey",
	"gym workout top",
	"athletic zip-up",
	// Smart Casual
	"casual blazer",
	"turtleneck sweater",
	"cable knit sweater",
	"crewneck sweatshirt",
];

/** Background locations - diverse college and social settings */
export const LOCATIONS = [
	// Campus
	"dorm room",
	"campus library",
	"red brick quad",
	"university hallway",
	"lecture hall",
	"study lounge",
	"campus lawn",
	"student center",
	// Social spots
	"coffee shop",
	"restaurant booth",
	"rooftop bar",
	"house party",
	"music festival",
	// Active/Sports
	"gym",
	"basketball court",
	"hiking trail",
	"beach",
	"swimming pool",
	// Outdoors
	"sunny park",
	"city street",
	"urban rooftop",
	"golden hour field",
	"sunset background",
	// Home/Casual
	"bedroom",
	"living room couch",
	"kitchen",
	"bathroom mirror selfie",
];

/** Expressions/Vibes for natural poses */
export const VIBES = [
	// Happy/Positive
	"smiling warmly",
	"laughing",
	"grinning",
	"smirking",
	"soft smile",
	"beaming",
	// Neutral/Casual
	"relaxed",
	"calm",
	"neutral",
	"candid",
	"natural",
	// Confident
	"confident",
	"self-assured",
	"poised",
	// Thoughtful/Serious
	"serious",
	"thoughtful",
	"contemplative",
	"focused",
	// Playful
	"playful",
	"cheeky",
	"mischievous",
	"flirty",
];

// =============================================================================
// FACIAL FEATURES (For breaking "same-face" AI syndrome)
// =============================================================================

/** Face shapes for diversity */
export const FACE_SHAPES = [
	"round face",
	"oval face",
	"square jaw",
	"heart-shaped face",
	"long face",
	"diamond-shaped face",
	"rectangular face",
];

/** Nose types */
export const NOSE_TYPES = [
	"button nose",
	"prominent nose",
	"wide nose",
	"narrow nose",
	"aquiline nose",
	"flat nose bridge",
	"upturned nose",
];

/** Eye shapes */
export const EYE_SHAPES = [
	"almond eyes",
	"round eyes",
	"hooded eyes",
	"monolid eyes",
	"downturned eyes",
	"wide-set eyes",
	"close-set eyes",
];

/** Unique distinguishing features */
export const UNIQUE_FEATURES = [
	// Skin features
	"freckles on cheeks",
	"freckles across nose",
	"clear skin",
	"light acne",
	"beauty mark on face",
	"beauty mark near lips",
	"rosy cheeks",
	// Eyebrows
	"thick eyebrows",
	"thin eyebrows",
	"bushy eyebrows",
	"arched eyebrows",
	"straight eyebrows",
	// Lips
	"thin lips",
	"full lips",
	"cupid's bow lips",
	// Facial structure
	"dimples",
	"prominent cheekbones",
	"high cheekbones",
	"soft features",
	"sharp features",
	"angular jawline",
	// Smile
	"wide smile",
	"subtle smile",
	"slightly crooked smile",
	"gap between front teeth",
	// Other
	"visible laugh lines",
	"under-eye circles",
	"defined nasolabial folds",
];

/** Chin types to override model bias */
export const CHIN_TYPES = [
	"rounded chin",
	"pointed chin",
	"soft chin",
	"small chin",
	"prominent chin",
	"receding chin",
	"double chin",
];

// =============================================================================
// UTILITY FUNCTIONS
// =============================================================================

/** Pick random element from array */
export const pick = <T>(arr: T[]): T =>
	arr[Math.floor(Math.random() * arr.length)];

/** Fisher-Yates shuffle for randomization */
export function shuffle<T>(array: T[]): T[] {
	const arr = [...array];
	for (let i = arr.length - 1; i > 0; i--) {
		const j = Math.floor(Math.random() * (i + 1));
		[arr[i], arr[j]] = [arr[j], arr[i]];
	}
	return arr;
}
